version: '3.4'

services:
  mssqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
        - 1433:1433
    environment:
        SA_PASSWORD: 'tester@123'
        ACCEPT_EULA: 'Y'

  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile

  foodservice:
    image: ${DOCKER_REGISTRY-}foodservice
    build:
      context: .
      dockerfile: FoodService/Dockerfile


  courierservice:
    image: ${DOCKER_REGISTRY-}courierservice
    build:
      context: .
      dockerfile: CourierService/Dockerfile


  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile


  library:
    image: ${DOCKER_REGISTRY-}library
    build:
      context: .
      dockerfile: Library/Dockerfile